import Head from "next/head";

type PageProps = {
  children: React.ReactNode;
  title: string;
};

const Page = ({ children, title = "" }: PageProps) => {
  const pageTitle = `Concept AI Art - ${title}`;
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {children}
      </main>
    </>
  );
};

export default Page;
